<?php
namespace common\components;

class ApiBaseController extends XController {
	public $enableCsrfValidation = false;
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}
}