<?php
namespace common\components;
/**
 * 接口基类
 * Class ApiBaseController
 * @package common\components
 */
class ApiBaseController extends XController {
	public $enableCsrfValidation = false;
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}
	
}