<?php
/**
 * Created by PhpStorm.
 * User: ioioj5
 * Date: 2017/1/23
 * Time: 15:03
 */

namespace backend\models;


class GoodsTags extends \common\models\GoodsTags {
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}

	/**
	 * 获取标签列表
	 * @param $limit
	 * @param $offset
	 *
	 * @return array
	 */
	public static function getGoodsTagsList($limit, $offset){
		$fields = parent::find()->limit($limit)->offset($offset)->orderBy('id DESC')->all();
		$count = parent::find()->count();

		return ['fields'=>$fields, 'count'=>$count];
	}
}