<?php
/**
 * Created by PhpStorm.
 * User: ioioj5
 * Date: 2017/5/9
 * Time: 17:40
 */

namespace backend\models;


class Log extends \common\models\Log {
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}


	public static function getLogList($condition = [], $limit = 0, $offset = 0){
		$query = parent::find();
		if(! empty($condition)) {
			$query->where($condition);
		}
		if($limit > 0) {
			$query->limit($limit);
		}
		if($limit > 0 and $offset >= 0) {
			$query->off($offset);
		}
		$fields = $query->orderBy('id DESC')->all();

		$query = parent::find();
		if(! empty($condition)) {
			$query->where($condition);
		}
		$count = $query->count();

		return ['fields'=>$fields, 'count'=>$count];
	}
}