<?php
/**
 * Created by PhpStorm.
 * User: ioioj5
 * Date: 2017/5/9
 * Time: 17:40
 */

namespace backend\models;


class Log extends \common\models\Log {
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}

	/**
	 * 格式化显示错误级别信息
	 * @param int $level
	 *
	 * @return string
	 */
	public static function level($level = 0){
		if($level < 1) return 'unknown';

		if($level == 1){
			return '<span class="label label-danger">Error</span>';
		}elseif($level == 2) {
			return '<span class="label label-warning">Warning</span>';
		}elseif($level == 4) {
			return '<span class="label label-info">Info</span>';
		}elseif($level == 8) {
			return '<span class="label label-primary">Trace</span>';
		}else {
			return 'unknown';
		}
	}


	/**
	 * 获取日志列表
	 * @param array $condition
	 * @param int   $limit
	 * @param int   $offset
	 *
	 * @return array
	 */
	public static function getLogList($condition = [], $limit = 0, $offset = 0){
		$query = parent::find();
		if(! empty($condition)) {
			$query->where($condition);
		}
		if($limit > 0) {
			$query->limit($limit);
		}
		if($limit > 0 and $offset >= 0) {
			$query->off($offset);
		}
		$fields = $query->orderBy('id DESC')->all();

		$query = parent::find();
		if(! empty($condition)) {
			$query->where($condition);
		}
		$count = $query->count();

		return ['fields'=>$fields, 'count'=>$count];
	}
}