<?php
namespace backend\models;


class Tags extends \common\models\Tags {
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}

	/**
	 * 获取标签列表
	 * @param $limit
	 * @param $offset
	 *
	 * @return array
	 */
	public static function getTagsList($limit, $offset){
		$fields = parent::find()->limit($limit)->offset($offset)->orderBy('id DESC')->all();

		$count = parent::find()->count();

		return ['fields'=>$fields, 'count'=>$count];
	}

	/**
	 * 删除标签
	 * @param int $id
	 *
	 * @return false|int
	 * @throws \Exception
	 */
	public static function deleteTags($id = 0){
		if($id < 1) throw new \Exception('参数错误');
		$goods = parent::findOne($id);
		return $goods->delete();
	}
}