<?php
/**
 * Created by PhpStorm.
 * User: ioioj5
 * Date: 2016/10/16
 * Time: 20:43
 */

namespace backend\models;


class User extends \common\models\User {
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}

	/**
	 * 获取商品列表
	 * @param $limit
	 * @param $offset
	 *
	 * @return array
	 */
	public static function getUserList($limit, $offset){
		$fields = parent::find()->limit($limit)->offset($offset)->orderBy('id DESC')->all();

		$count = parent::find()->count();

		return ['fields'=>$fields, 'count'=>$count];
	}

	/**
	 * 删除商品
	 *
	 * @param int $id
	 *
	 * @return false|int
	 * @throws \Exception
	 */
	public static function deleteUser($id = 0){
		if($id < 1) throw new \Exception('参数错误');
		$goods = parent::findOne($id);
		return $goods->delete();
	}
}