<?php
/**
 * Created by PhpStorm.
 * User: ioioj5
 * Date: 2017/6/3
 * Time: 16:39
 */

namespace console\controllers;


use common\components\ConsoleBaseController;
use common\components\Snoopy;

class SpiderController extends ConsoleBaseController {
	public $snoopy;
	public $time;

	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
		$this->snoopy = new Snoopy();
		$this->snoopy->agent   = 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1';
		$this->snoopy->cookies['KDTSESSIONID'] = 'pj67brvqcsd58vor45iktq61u4';
		$this->snoopy->cookies['_canwebp'] = '1';
		$this->snoopy->cookies['_kdt_id_'] = '108238';
		$this->snoopy->cookies['css_base'] = '2b5be3d3c89f094';
		$this->snoopy->cookies['css_base_wxd'] = 'f085f8a64c97ca9';
		$this->snoopy->cookies['css_showcase'] = '0817299c310839b';
		$this->snoopy->cookies['css_new_order'] = '2b8b92a5ab81599';
		$this->snoopy->cookies['css_goods'] = '055a5c77a2b8fe7';
		$this->snoopy->cookies['css_trade'] = '66a1b0138c464fd';
		$this->snoopy->cookies['css_buyer'] = '24766460e2f9208';
		$this->snoopy->cookies['css_showcase_admin'] = 'f9dea305248ccec';
		$this->snoopy->cookies['redirect'] = 'http%3A%2F%2Fwww.youzan.com%2Fv2%2Ffenxiao%2Fmarket%3Fgoods_fx%3D1';
		$this->snoopy->cookies['gr_user_id'] = 'a2df4c68-64ea-4a36-a1ed-936422ea03dd';
		$this->snoopy->cookies['TJ_FROM'] = 'kdt';
		$this->snoopy->cookies['UM_distinctid'] = '15c6d1444de103-07738ed05c6378-8373f6a-15f900-15c6d1444df100';
		$this->snoopy->cookies['CNZZDATA5351147'] = 'cnzz_eid%3D300949633-1496474887-https%253A%252F%252Flogin.youzan.com%252F%26ntime%3D1496474887';
		$this->snoopy->cookies['retrieve_response'] = 'e2a41f6b2085918aaa11b408f0d22415';
		$this->snoopy->cookies['avatar'] = 'https%3A%2F%2Fdn-kdt-img.qbox.me%2Fupload_files%2Favatar.png';
		$this->snoopy->cookies['mobile'] = '15652265362';
		$this->snoopy->cookies['sid'] = 'b8186579b7c72fccbf79978486f36064';
		$this->snoopy->cookies['sKey'] = 'chppyIyekyS-3TUPze_8RgTbffTQ8H7f8TbIqdKrsnY%3D';
		$this->snoopy->cookies['user_id'] = '34744430';
		$this->snoopy->cookies['user_weixin'] = '%2B86-15652265362';
		$this->snoopy->cookies['user_nickname'] = '15652265362';
		$this->snoopy->cookies['kdtnote_fans_id'] = '0';
		$this->snoopy->cookies['Hm_lvt_7fff7ceede91c07fb0a2f9c1850d7987'] = '1496478664';
		$this->snoopy->cookies['kdt_id'] = '17965665';
		$this->snoopy->cookies['team_auth_key'] = 'f6942b63f9abdb405faf50ba9eb19f64';
		$this->snoopy->cookies['gr_session_id_767813e963734402a8256e1096b88331'] = '3c494798-209b-420d-8cff-a50b1b6f39fc';
		$this->snoopy->cookies['gr_cs1_3c494798-209b-420d-8cff-a50b1b6f39fc'] = 'user_id%3A34744430';



		$this->snoopy->accept = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
		$this->snoopy->host = 'www.youzan.com';
		//$this->snoopy->referer = 'http://www.youzan.com/v2/fenxiao/market/goods/woman?order=desc&orderby=fx_count';

		$this->time = time();
	}

	public function actionIndex(){
		$this->snoopy->fetch("http://www.youzan.com/v2/fenxiao/market/detail.json?alias=r8ivwibx");
		$results = $this->snoopy->results;
		print_r($results);
	}
}