<?php
/**
 * Created by PhpStorm.
 * User: ioioj5
 * Date: 2017/5/20
 * Time: 13:28
 */

namespace frontend\models;


class GoodsRedis extends \common\models\GoodsRedis {
	public function init () {
		parent::init (); // TODO: Change the autogenerated stub
	}

	public static function getOne($goodsId = 0){
		if($goodsId < 1) return false;

		return parent::find()->where(['id'=>$goodsId, 'status'=>1])->one();
	}
}